### ISSUE TITLE
Historical data

### ISSUE THREAD

**Issue by emartynov** [alfredapp/currency-converter-workflow#1]
### Feature details

Hi people,

API supports the historical data. Getting a rate for a pair of currencies on a specific day would be great.

**Comment by vitorgalvao** [comment]
Thank you for the request.

As per [their documentation](https://www.exchangerate-api.com/docs/historical-data-requests) (emphasis added):

> Our Historical Exchange Rates API endpoint lets you fetch all the exchange rate data we have available for a specific day in the past. **It's only available to users on our Pro, Business or Volume plans.**

One explicit goal of this workflow is to work without setup. That’s one of the reasons this API was chosen, as it doesn’t require futzing from the user. The workflow is open-source so you’re encouraged to adapt it to your own needs.

**Comment by emartynov** [comment]
Clear! Maybe with ChatGPT's help, I can update the code using the Apple script.
