### ISSUE TITLE
Flag of south korea is wrong

### ISSUE THREAD

**Issue by CreamNuts** [alfredapp/currency-converter-workflow#2]
### Workflow version

2024.2

### Alfred version

5.5.1

### macOS version

Sonoma 14.4

### Debugger output

```alfred_debugger
Image is wrong.
```

### More details

<img width="741" alt="image" src="https://github.com/user-attachments/assets/f9badfd6-40d8-4209-8979-7fae80a55cca">

**Comment by vitorgalvao** [comment]
Thank you. Looks like the SVG got mangled in the conversion. Fixed in 2024.3.
